name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2

      - name: Lint
        run: deno task lint

      - name: Check
        run: deno task check

      - name: Test
        run: deno task test

  build:
    if: startsWith(github.ref, 'refs/tags/')
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2

      - name: Compile binaries
        run: ./scripts/build.sh

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ github.ref_name }} --generate-notes ./dist/*.tar.gz

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Publish package
        run: npx jsr publish
